USE defaultdb;

ALTER TABLE records ADD COLUMN IF NOT EXISTS soft_copy LONGBLOB NULL;
ALTER TABLE records ADD COLUMN IF NOT EXISTS soft_copy_name VARCHAR(255) NULL;
ALTER TABLE records ADD COLUMN IF NOT EXISTS soft_copy_type VARCHAR(120) NULL;
ALTER TABLE records ADD COLUMN IF NOT EXISTS soft_copy_size INT NULL;
